### ISSUE TITLE
OSS range get request not working in 2.8.2

### ISSUE THREAD

**Issue by shreyasshinde** [aliyun/aliyun-oss-java-sdk#127]
A GetObjectRequest with a specific range does not get honored in the OSS client. Instead, the object from the start is returned in the response.

```
OSSClient oss = new OSSClient("https://oss-cn-beijing.aliyuncs.com", "myUsername", "myKey");
final GetObjectRequest get = new GetObjectRequest("myBucket", "myFileInBucket");
int start = 131140;
int end = 134990;
get.setRange(start, end);
final OSSObject object = oss.getObject(get);
InputStream is = object.getObjectContent();
try {
		is.read(ossBuffer);
		System.out.println("Output from OSS: ");
		System.out.println(Arrays.toString(ossBuffer));
	} catch (IOException e) {
		e.printStackTrace();
	} finally {
		is.close();
	}
```

Is there anything incorrect in the code above? This always returns the start of the file instead of within the file.

**Comment by baiyubin** [comment]
Thanks for pointing out this. Actually the way that OSS handles unexpected range header is different from S3. 
You can see: https://www.alibabacloud.com/help/doc-detail/31980.htm?spm=a3c0i.o31855en.a3.6.60ca1dd2oo3MVL (second bullet in "Detail analysis" section)
  •  If the Range parameter is used in the request header, the returned message includes the length of the entire file and the range returned for the request. For example, if the returned message is Content-Range: bytes 0-9/44, it means that the length of the entire file is 44, and the range returned is 0 to 9. If the range requirement is not met, the system transfers the entire file and does not include Content-Range in the result.

We know that this behavior does not strictly follow HTTP protocal, so we are trying to fix this. As you know, we have to be careful to deal with this kind of "change", because some customer's application might rely on this behavior...
Current plan is to fix this in the early of May.

**Comment by huiguangjun** [comment]
https://www.alibabacloud.com/help/en/object-storage-service/latest/range-download-8
